### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'kernel_manifold')

### ISSUE THREAD

**Issue by Maxime91860** [geomstats/examples#10]
Hi,

I tried to run the deep learning example, but I encountered some issues. 

I applied the procedure from examples/nips2018/deep_learning/README.md

I use python 3.6 anaconda environment, and these versions :
* tensorflow       1.8.0 (patched with the copy of variables
* geomstats       1.9 (installed from pip install geomstats)
* keras               2.1.6 (installed from  examples/nips2018/deep_learning/keras)

When I try to run with `./run.sh` I have this error:

```bash
Using TensorFlow backend.
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "mnist_hypersphere.py", line 54, in <module>
    kernel_manifold=Hypersphere(hypersphere_dimension)))
  File "build/bdist.linux-x86_64/egg/keras/legacy/interfaces.py", line 91, in wrapper
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 465, in __init__
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 104, in __init__
  File "build/bdist.linux-x86_64/egg/keras/engine/base_layer.py", line 122, in __init__
TypeError: ('Keyword argument not understood:', 'kernel_manifold')
```

Do you have any idea how to fix it ?

Thanks

**Comment by johmathe** [comment]
Let me have a look today. Stay tuned.

**Comment by johmathe** [comment]
It seems to me that you might have another version of keras installed and built.

**Comment by johmathe** [comment]
Did this solve your issue?

**Comment by mbauw** [comment]
I encountered the same error (whether running `./run.sh ` or `python geomstats_examples/applications/deep_learning/cifar_10_resnet_hypersphere.py` in a python 3.6.7 virtual env). This error happens whenever (I carefully repeated this a couple of times to reproduce the error) I... :

1. ...create a python3 venv (Python 3.6.7)
2. install, using `pip`, tensorflow (tried `tensorflow-gpu` 1.13.1,` tf-nightly-gpu` 1.14.0, `tensorflow` 1.13.1 - using CPU), `geomstats` and `keras`
3. try to launch` ./run.sh` **_before_** following the readme patch instructions

So, from my limited experience of this error message, you didn't patch your tensorflow according to the readme of the applications repo. One explanation I would see it that you're working inside a virtual env but using the readme pasted command line `sudo python3 setup.py install` **_instead of using the virtual env friendly version_** `python3 setup.py install` (using the pasted readme version will update your actual system keras, not the virtual env keras, if I'm not mistaking).

**_This error disappears after following the patch instructions_**, leading to... another error about which I'm going to create another issue ;-)

_**One possible explanation for those issues**_, at least on my side: the readme of applications/deep_learning/ says _"You will also need a tensorflow version 1.8."_ whereas geomstats/requirements.txt says _"tensorflow>=1.12"_. So, worst case scenario, even if it sounds illogical (hence my hopeful tests with tf GPU 1.13.1, nightly 1.14.0 and tf CPU 1.13.1), the library itself works on recent tensorflow but not the examples provided... Otherwise, well, I didn't find the complete solution to this yet !
